default: &default
  access_key_id: 'default_key'
  secret_access_key: 'default_secret_access_key'
  authentication:
    enabled: false

test:
  <<: *default
  access_key_id: 'test_env_key'

development:
  <<: *default

production:
  <<: *default
  authentication:
    enabled: true
    username: foo
    password: bar
